github.com:
    users:
        AiDN-Dev:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: AiDN-Dev
